/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author khura
 */

// Represents a Playbox's products with specific attributes like name, cost, retail, and # of products sold
public class productData {

    private String productName;
    private double cost;
    private double retailPrice;
    private int numbersSold;
    private double revenue;
    private double profits;

    /**
     * Constructs a data entry with default values.
     */
    public productData() {
        productName = "";
        cost = 0;
        retailPrice = 0;
        numbersSold = 0;
        revenue = 0;
        profits = 0;
    }

    /**
     * Constructs a product data entry with specified attributes.
     *
     * @param name                 The name of the product
     * @param productCost          The cost of the product.
     * @param productRetailPrice   The retail price of the product.
     * @param numberOfProductsSold The total number sold of the product.
     */
    public productData(String name, double productCost, double productRetailPrice, int numberOfProductsSold) {
        productName = name;
        cost = productCost;
        retailPrice = productRetailPrice;
        numbersSold = numberOfProductsSold;
        revenue = productRetailPrice * numberOfProductsSold;
        profits = revenue - (numberOfProductsSold * productCost);
    }

    // Getters and setters

    /**
     * Gets the name of the product.
     *
     * @return The name of the product.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Sets the name of the product.
     *
     * @param newName The new name of the product.
     */
    public void setProductName(String newName) {
        this.productName = newName;
    }

    /**
     * Gets the cost of the product.
     *
     * @return The cost of the product.
     */
    public double getCost() {
        return this.cost;
    }

    /**
     * Sets the cost of the product.
     *
     * @param newCost The new cost of the product.
     */
    public void setCost(double newCost) {
        this.cost = newCost;
    }

    /**
     * Gets the retail price of the product.
     *
     * @return The retail price of the product.
     */
    public double getRetailPrice() {
        return this.retailPrice;
    }

    /**
     * Sets the retail price of the product.
     *
     * @param newPrice The new retail price of the product.
     */
    public void setRetailPrice(double newPrice) {
        this.retailPrice = newPrice;
    }

    /**
     * Gets the total number of products sold.
     *
     * @return The total number of products sold.
     */
    public int getNumbersSold() {
        return this.numbersSold;
    }

    /**
     * Sets the total number of products sold.
     *
     * @param newNumberSold The new total number of products sold.
     */
    public void setNumbersSold(int newNumberSold) {
        this.numbersSold = newNumberSold;
    }

    /**
     * Gets the total revenue generated by the product.
     *
     * @return The total revenue generated by the product.
     */
    public double getRevenue() {
        return this.revenue;
    }

    /**
     * Sets the total revenue generated by the product.
     *
     * @param newRevenue The new total revenue generated by the product.
     */
    public void setRevenue(double newRevenue) {
        this.revenue = newRevenue;
    }

    /**
     * Gets the total profits generated by the product.
     *
     * @return The total profits generated by the product.
     */
    public double getProfits() {
        return this.profits;
    }

    /**
     * Sets the total profits generated by the product.
     *
     * @param newProfits The new total profits generated by the product.
     */
    public void setProfits(double newProfits) {
        this.profits = newProfits;
    }

    @Override
    public String toString() {
        return String.format("%25s\t%25.2f\t%25.2f\t%25d\t%25.2f\t%25.2f\t\n", productName, cost, retailPrice, numbersSold, revenue, profits);
    }

    /**
     * Generates a string representation for saving data to a file.
     *
     * @return A formatted string representing the data for saving to a file.
     */
    public String saveToFile() {
        String output = String.format("%s,%.2f,%.2f,%d,%.2f,%.2f,", productName, cost, retailPrice, numbersSold, revenue, profits);
        return output;
    }
}

